### ISSUE TITLE
Upgrade Ownable contract to latest version

### ISSUE THREAD

**Issue by miguelcalero** [alastria/alastria-identity#67]

**Comment by Jiang-dxc** [comment]
@nefera6060 we need to firstly update all our smart contracts to the last version of solc before moving this task forward(updating owable to last openzeppelin version, which uses solc 0.6.0 ), otherwise we may broke the existing contracts and application compiling same contract with different solc versions, ownable is inherited by other contracts.

**Comment by Jiang-dxc** [comment]
@nefera6060 we need to firstly update all our smart contracts to the last version of solc before moving this task forward(updating owable to last openzeppelin version, which uses solc 0.6.0 ), otherwise we may broke the existing contracts and application compiling same contract with different solc versions, ownable is inherited by other contracts.
